### ISSUE TITLE
"Get Involved" Card tweaks

### ISSUE THREAD

**Issue by ebarry** [publiclab/design#4]
The bottom line on the front of the donation card lists publiclab.org (see image). the URL should be left justified so that people have room to write specific links to direct people to.

![donation-card-front-noborder](https://cloud.githubusercontent.com/assets/161439/4409279/e81ff8e4-44db-11e4-90a3-ba512bc27938.jpg)

**Comment by jywarren** [comment]
can you make sure Natalie knows about this as she'll be the one to re-order.

**Comment by ebarry** [comment]
@Nataliegurl see this issue about needing more room around the URL

**Comment by Nataliegurl** [comment]
I see it, can it be changed in the template?

## 

Natalie Mayorga

_Kits Initiative ManagerPublic Lab412 NW Couch, Ste. 401Portland, OR 97209_

_T: 503.902.5874_

_F: 504.324.0401_

_Natalie@publiclab.org Natalie@publiclab.org_

_www.publiclab.org http://www.publiclab.org_

_FB: www.facebook.com/PublicLab http://www.facebook.com/PublicLab_

_Twitter: @PublicLab, @natcat5050_
_Instagram: public_lab_

**Comment by jywarren** [comment]
can you ping me next time you print them? sure.

**Comment by Nataliegurl** [comment]
yep

## 

Natalie Mayorga

_Kits Initiative ManagerPublic Lab412 NW Couch, Ste. 401Portland, OR 97209_

_T: 503.902.5874_

_F: 504.324.0401_

_Natalie@publiclab.org Natalie@publiclab.org_

_www.publiclab.org http://www.publiclab.org_

_FB: www.facebook.com/PublicLab http://www.facebook.com/PublicLab_

_Twitter: @PublicLab, @natcat5050_
_Instagram: public_lab_

**Comment by jywarren** [comment]
Actually i think we may want to leave as-is since I sometimes put my email address on it, like [jeff@]publiclab.org

Is that OK? Can we close this issue?

**Comment by Nataliegurl** [comment]
@ebarry ? I'm fine with it, so there's room on both sides.

**Comment by Nataliegurl** [comment]
This issue was closed, but I just want to bring up that we are going to
need to reorder very soon, and have them reprinted. So now is the time to
request changes.

## 

Natalie Mayorga

_Kits Initiative ManagerPublic Lab412 NW Couch, Ste. 307Portland, OR 97209_

_T: 971.570.5095_

_F: 504.324.0401_

_Natalie@publiclab.org Natalie@publiclab.org_

_www.publiclab.org http://www.publiclab.org_

_FB: www.facebook.com/PublicLab http://www.facebook.com/PublicLab_

_Twitter: @PublicLab, @natcat5050_
_Instagram: public_lab_
